# Generated by Django 3.2.7 on 2025-01-08 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='total_floor',
            new_name='total_floors',
        ),
    ]
